version: '3'

networks:
    network-curriculo-dev:
        driver: bridge
        ipam:
          config:
            - subnet:  10.10.0.0/16       
services:
  postgres:   
      image: postgres:9.6
      container_name: postgres-curriculo-dev
      expose: 
        - 5432
      networks:
        network-curriculo-dev:
          ipv4_address: 10.10.0.3
      ports:
        - "5432:5432"
      environment: 
        - POSTGRES_USER=ivan
        - POSTGRES_PASSWORD=curriculo
        - POSTGRES_DB=curriculo-dev
  