spring:
  profiles:
    active: '@spring.profiles.to.activate@'
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  jackson:
    default-property-inclusion: NON_NULL
  thymeleaf:
    cache: 'false'
banco:
  inicializar: 'true'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG
    web: DEBUG
springdoc:
  packagesToScan: dev.ivanqueiroz.curriculo
jwt:
  secret: ${SECURE_KEY:secreto}
