CREATE TABLE CURRICULO
(
  ID            INTEGER       NOT NULL,
  PRIMEIRO_NOME VARCHAR(100)  NOT NULL,
  ULTIMO_NOME   VARCHAR(100)  NOT NULL,
  PROFISSAO     VARCHAR(200)  NOT NULL,
  RESUMO        VARCHAR(9000) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE HISTORICO
(
  ID              INTEGER       NOT NULL,
  TITULO          VARCHAR(100)  NOT NULL,
  INSTITUICAO     VARCHAR(100)  NOT NULL,
  DESCRICAO       VARCHAR(400)  NOT NULL,
  LINK_REFERENCIA VARCHAR(1024) NOT NULL,
  ANO_INICIO      VARCHAR(4)    NOT NULL,
  ANO_FIM         VARCHAR(4)    NOT NULL,
  TIPO_HISTORICO  VARCHAR(20)   NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_HISTORICO INCREMENT BY 1 MINVALUE 1 START WITH 1;

CREATE TABLE CURRICULO_HISTORICOS
(
  CURRICULO_ID  INTEGER NOT NULL,
  HISTORICOS_ID INTEGER NOT NULL,
  PRIMARY KEY (CURRICULO_ID, HISTORICOS_ID)
);

CREATE TABLE CONTATO
(
  ID           INTEGER      NOT NULL,
  VALOR        VARCHAR(100) NOT NULL,
  DESCRICAO    VARCHAR(100) NOT NULL,
  TIPO_CONTATO VARCHAR(20)  NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CURRICULO_CONTATOS
(
  CURRICULO_ID INTEGER NOT NULL,
  CONTATOS_ID  INTEGER NOT NULL,
  PRIMARY KEY (CURRICULO_ID, CONTATOS_ID)
);

CREATE SEQUENCE SEQ_CONTATO INCREMENT BY 1 MINVALUE 1 START WITH 1;

CREATE TABLE CONHECIMENTO
(
  ID                INTEGER      NOT NULL,
  TITULO            VARCHAR(100) NOT NULL,
  NIVEL             REAL         NOT NULL,
  TIPO_CONHECIMENTO VARCHAR(20)  NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CURRICULO_CONHECIMENTOS
(
  CURRICULO_ID     INTEGER NOT NULL,
  CONHECIMENTOS_ID INTEGER NOT NULL,
  PRIMARY KEY (CURRICULO_ID, CONHECIMENTOS_ID)
);

CREATE SEQUENCE SEQ_CONHECIMENTO INCREMENT BY 1 MINVALUE 1 START WITH 1;
