CREATE TABLE USUARIO_ROLE
(
    ID         INTEGER NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    ROLE_ID    INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID)
);

CREATE SEQUENCE SEQ_USUARIO_ROLE INCREMENT BY 1 MINVALUE 1 START WITH 1;
